root = "."
tmp_dir = "cmd/catalog/tmp"

[build]
  cmd = "go build -o ./cmd/catalog/tmp/main ./cmd/catalog"
  entrypoint = ["./cmd/catalog/tmp/main"]
  include_ext = ["go", "proto"]
  exclude_dir = ["gen", "cmd/catalog/tmp", "cmd/configuration/tmp", "cmd/gateway/tmp"]
  delay = 1000
  poll = true
  poll_interval = 1000
  stop_on_error = true